server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
  port: 9050
  max-http-request-header-size: 785000
  tomcat:
    accesslog:
      enabled: true
    threads:
      min-spare: 50
      max: 350
spring:
  application:
    name: springboot-web-demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2
    username: saber66
    password: AdminSaber66
    hikari:
      schema: test2
      idle-timeout: 10000
      connection-timeout: 10000
      minimum-idle: 2
      maximum-pool-size: 8
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


service:
  baseUrl: "/services/${spring.application.name}"
  swagger:
    version: 'version1.0.0-1403/01/11'
    title: 'springboot web demo'
    description: 'springboot web demo'

springdoc:
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    display-operation-id: true
    tags-sorter: alpha
  api-docs:
    path: "/services/${spring.application.name}/v3/api-docs"
