server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
  port: 9050
  max-http-request-header-size: 785000
  tomcat:
    accesslog:
      enabled: true
    threads:
      min-spare: 50
      max: 350
spring:
  application:
    name: springboot-web-demo


service:
  baseUrl: "/services/${spring.application.name}"
  swagger:
    version: 'version1.0.0-1403/01/11'
    title: 'springboot web demo'
    description: 'springboot web demo'

springdoc:
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    display-operation-id: true
    tags-sorter: alpha
  api-docs:
    path: "/services/${spring.application.name}/v3/api-docs"
